# https://raw.githubusercontent.com/kubernetes-sigs/external-dns/master/charts/external-dns/values.yaml

external-dns:
  provider: pihole
  txtOwnerId: homelab
  env:
    - name: EXTERNAL_DNS_PIHOLE_SERVER
      value: http://192.168.10.5
    - name: EXTERNAL_DNS_PIHOLE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: external-dns-secret
          key: EXTERNAL_DNS_PIHOLE_PASSWORD
  extraArgs:
    - --annotation-filter=external-dns.alpha.kubernetes.io/exclude notin (true)

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
