---
- name: Does the k3d binary exists?
  stat:
    path: '{{ k3d_path_bin }}'
  register: k3d_binary

- name: Download k3d installer file
  ansible.builtin.get_url:
    url: '{{ k3d_install_url }}'
    dest: '{{ role_path }}/files/bin/install_k3d.sh'
    mode: '0755'
  delegate_to: localhost
  run_once: true
  register: k3d_install_file
  when: not k3d_binary.stat.exists

- name: Copy k3s installer file to nodes
  ansible.builtin.copy:
    src: bin/install_k3d.sh
    dest: '{{ k3d_path_tmp }}'
    owner: '{{ deploy_account.user }}'
    group: '{{ deploy_account.group }}'
    mode: '0755'
  when: not k3d_binary.stat.exists

- name: Install k3d
  command: '{{ k3d_path_tmp }}'
  when: not k3d_binary.stat.exists

- name: Clean up the k3d installer file
  file:
    path: '{{ k3d_path_tmp }}'
    state: absent
  when: not k3d_binary.stat.exists
