apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-secret
  namespace: default
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgAeuuSh46pCS9rcS0b9ymva6i7++4XElXHZnjeBHBaOFYmQpO265H84W7QWFYV4qDWuACW8OiHhCwPqdmMdnOtoN6UwEKIhe3lI2YN9/XoGsj6TyBz8DUaRE8Thg32uYeLkWSnoroo0IKktS8QfY2UaQQR5sQgfZUDeX+5lvYNf+J6jaGARJ98TXA2olr+CRnQLS6B3yZpAQDi8FZwym8YqpDvnxb1K6rq3zOTy7MnNXU2WIioZ15jKP4qmQexo9P5C07YfSPhGRzwXZLqAEnMY49ptUzkUWqtGXCFZbPJUWx4n494jXGRGIXVZP2CzxEz/IzWG5iJerWAUoK27HYkyhI0pzZRK+MOipdTOxPsbhOAEKsNiQRZhRYa0+PPnNz489AWCdcpo8V6DnY6h1w7OPBUDHysZ3B3MVmPrXuhPHWbO/ToZhZumcKNCjVD02OTvlYVuan+olYMtJ3djLDK3GkM/kxX6tYcoVagnxquD8NPDfpzhdsFEtlSiBjNcniNDYutEkQgwXr/eqQh71YhbKuJf3ieBX+qlz9Xql/G7x8egcedveof6i/Z/eAN07tjebNRdFFd5TA2H1Nc00PWFkqHrgLOJR7Dy4siWK4kwH6UCMPEK7m8A1GpzdBJzTuEoU5GTyApMeGW/YxB07TXHjURmecOwoBI8/ifPozihOypH+EUYMa538vC7J/6gpsaU3Eeaw8IZ4Q==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-secret
      namespace: default
    type: Opaque
---
