apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-secret
  namespace: default
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgAkdeYl3wSeao7CZA8DFtq/OMJc0AvbWykFcK8W6DpSJILMp1TsZKocHZfO/a8NMSmH1gFIrKd1SM7wFCua4ILrqhb8AYnP87pvobkxAg4wCYOm4s7qtCR8o+B3fPNbtGqkG4/Fzn00nv/UJnc1KQsxCV1tn4R3E5fUWgMFCyjARpsAX8jqdazmEwVvYhNNqgCrItwDw+A4BTAQj3IDUyyIuk9xlOee8P6RBIhp+3YMLDQxkrn5HcSEfHKhYvOIvH57AiQPpH//iN7YMAKnUS0s7CokxfYgTdOiPH624pZw5PY8Hk5q9+Krz4+pPkAmiAifMyOhHzReawQMsvFm3l8p0xo+ymGYHErkYsP8jMs8SOzVTYSg8Aur3vuChGj00YhBdJMCwaPOiyDw+AuP3VF6GftmhqE31L4QxDP2B/bN0E6p7GwUesugc+OXvczm1TlpNn86Wh63mNNB3ayy7mXMjlkDOGed+4r/R/FZ/AiObq17icA5zB9NHjcmDVw2nOHEJJAepOwkPbkAyxmae84b2MV6eslXC7Qfm0J+4sB7XqaVMMXluN5dZztE7JCYJMD1naOrqpevaxgiAOnBYuX+/qzcZCkwrz3rWEVWlseemvFyh1DECD8svAShP0Nm8r+n+YRr5/Ujjhde/ii+UxME1cC65sSiKj+zwuotibkrdwAMAO5MIvA8kINPLCurjDdlo9ociupQRA==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-secret
      namespace: default
    type: Opaque
---
