apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-secret
  namespace: system
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgCiJsFdEVEoCdMIDGTVge3IyMJ9CWDHFiUkaQtEZmQXwdl6R2FCMtsrSqAoAK+PojojUfaFnnWZvOJl0ohp0FxTNWtliJhP7K8wW9koDcd4tD45wGurgsq56QSuy0V5mEiDcnMYee+ZtiHP1c1JL9q1JwAadXLQa1uJL6OOW8JDlHsIpGfRJFSKGBgpvW9puNt41sivUXQYUYiz07M5stFHBOxPnDFzVzIy1lUfBowNjarao9mTJpFwcfkGadwhbREKx1IlNe66Fsvl1+FgHCE0UsY9RlStSKquf/SH9Qmk+59zpP5fAN5z2lbdJ4mOHEyScioCGCdShqwgJC9dxEX95dJqMqgQd2FUkqHeKd5y3hYOMskzCo+PF5GZjc/5nkd4tjKeT/jYyofNAXN9sQR0cLmxbLXKUugDW1WzScYGh+THcgmuX5E4ZDgDI97szOitCirRlR3OmcWlEXJTfiVIcUhazo0nzfvFJM4doQLw0uk20SWsYZqfP6PYDFTgga2Bt3tcW6xhIJPZadpg7mJjKWJOwZ26r+A7alWkzLoObVg9L1cAmUHZyb5EtRcboHTW8R9jSfGm5UY1HjXSrb1P7i8UvdOTUCvHfUYHcxk+ek4AAT5ThbimqZNvv/AtynI/rVuNgSbdY3V6huO/rQxz2eE2s4363lMgNLHhtO2x2SwnONG0oOaCDyF/89Ww2vidqJD52m6mEg==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-secret
      namespace: system
    type: Opaque
---
