apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-secret
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgCGJNN6gCcG9CwX8DPmFaqM8DVOe6askJhxzLGN3YFy30JEi7ufML++6Fv5v5KEXPGhk4QJNT/JWmyNmZj2DiXCchEUIWaMtgwkTxW5c3kOqrgC9Wc2jQ8bZC4ixViQdlYErwTl2qmOwYqViI6Il0Q/Vw4ulLu1soYSBLFa8Sa5EIOHciP5zF9gVnzy+iduqCDkXIszMjHmQXu492awh4aOiaoTgyllGBNjdW3lF9ANfUCxVjDoYg4We6sl7EdCmKwhVIV+ktU7jSXz8gYqBUMxBhG1DmIDfki4H1v7Kpvfdug7IR5HwmpIaLW7WiCl1K7SVM7IPto9ziohPz/BRZRRaOQNPxbUqgJ9Zv2ElCB8VExijZD3yAE4pV+kQFcMarnu9+W2t7v+lPf0AOMgVB6DQHr6ZAVwDxTr/ndXI3R1fyHUtCchhlrrk90FmuARxu1KCtvp1MHdM6qQGtIFMIS40vGb5ebKJ/8BlTcAwNqE0bnfNatK50FTwX5LWl48ogdW27y7KUw5B1phvZVQNlkKMYDAg60G4V2U0lRvLsTGgGO6MWEmFx4tzU2RLKwHG+tvy/04LNz8R5HruACgo09i9CrvPymr4uf31CAr3blc+QdV7u2WACpQdLO+AcOuwwhcxV/1P3lcLAh+uXQe9LbfUBxR51dSJjdjVWgqBFKYWpfgHxnWvPuKLJYrmCzzKEhHQlffcdabaQ==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-secret
      namespace: {{ .Release.Namespace }}
    type: Opaque
---
