apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-secret
  namespace: default
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgAo38TVBXmjFLVWqomcqS4cuI+12QSZ1s/rrOgqSDpnIrirDSSyXZQhA8poSGDSkf8C+0JQpWC/ucsClH4rp5eMuWZEUfCGJHe1t2g4ebIAeI+eEuY+ccd05cDFG9/Vf0NMboOKwnjP0eRwH3Z0lOE8n+J47SX5+xObuCSwnFPRuSDo2wrCBoGPYxZNiqABU1QUuytDCTRmlhnmVdr/PrWqqpqpig7dnzeVtOL6IM6abdwCDC7JgrXj6QUpcfDayARrLzdHKHVT2pz53NOlq8BSYEkblzWuvwu+KqMtL9wAV4c/WwWbZgBwDx4G8ZwZ5ZGO7xeRadH+oMh8TDyxQrZx7NjKo7ivTzHuCpkW8AgnEfLSyfI2gFBNNK12B2icNIkUB5vnmqXeNY/yczUzX1/XKApPZogNp3EhKiv+prlLXJp5RbP1i54P4wLuYnXkDZGor/yuyX8e6kqOGIQfntXtBJlo4M82UVW1WvYjxKjsasLh/iF/p6JIs24vJef88mexFmk7t3DGsN65NOUnkQDLGLGJxqNQgZk6En2Yhq9BPrHyExacl47ljOMHBy9lTUk9hUXyQPMr9LDafyrdILGYR1Z0s09tallRPi3IoUUkFYHhmwpF4Uzoj1Ww3SWKY3qy3Z42dbBXQHL09bFrzB7NpUwuMIyd0PSUPx93i3UQOtN9sI/OVxJs2JgIZsxcvcUzN/EhIrEmrQ==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-secret
      namespace: default
    type: Opaque
---
