apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns
  namespace: '{{ .Release.Namespace }}'
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgAGDY3TkLbJ7zxBDcuW3oDfjnuDPzPlvBBGL5ypJLfscDijfLKv476PWNQ4KGNgUjRfgYk/3xamDWdfxUmQxO8wL5MBdusnYhehCwf4drSXY2tEQT4UDRUKWkIcKfZKtRBBTCf74OkmiVqtKNz3wkwxeyqRXqLuXFWL7c/OInxPKua3PEJD7agP4BCesOuLQJHrwmIXhGpqSRJwR1FdJX1vq4HyussyM8sI+Q9whMcDCRKw469gOzsnhwenM9SHTJGUTv3jZ4iyWZZok63cIBArZdPB5cglDL7JgErwM2vYpoaEtjbcF3wTyLoNrCGnkYRPpiIOxKSlh0Q0M7nEMxIFHJkDiNU2ys3GzSKG7tvRTivfil63rO2H+2igrLSGihTxbhkPFAFtlIeixjtiC2l7n3FpLDvj5JmbwIEBWfw7g/o4le4gxLtOsR1562ysQ374WAc4gLvondseUqqi3QFw4juzjybvC5ShlEk3vYdu91u8qnxl6VnTl05l6o39DL1Hptg8ETMj3NFMOhYKVSHFEeQWqVpYfSDZQ9JluIczzuc1EkxOgiPhkwcTh8mBRjjCMuJ7cl/w34WOIXA5Tu9IyJl+EtCwCIi8ttZNomiDsIWfWkKEbQXjUKd4a82KIhlrq0qQYFgrAfTqS1WBKFFOw8vua7LOIq3n3mVAFeTX0KUmXk/nZPv+qV0UWcy2Gy0AANAHtuT/0w==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns
      namespace: '{{ .Release.Namespace }}'
    type: Opaque
---
