apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-secret
  namespace: '{{ .Release.Namespace }}'
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgCHAX1qCk1b0pwUWcoyV6sAADmXdg+DaQXvf6aUnAR1flN/4XjxCPpaQMtpEM2xw1gzNe2i4YQafbrrANINDVmZ07NQSGelJ5bv8mT2w7gqt8O2gTTObuk+nCH7xtMPRbOMLkjWzSRgCjM8ltv9YZ8V8JyJPay/nH+JGcb337M+nImJ5TX/r6xJyeG0B1KsRoYsEIM2pmmepnk38jg7CInF6F3W0OJ9RbDodKVQIViErVmgZBv4jwYr8T/8ROgHlSrSnKS4uDFOggcwOnicP0jGbkeTiFTOeNeqK2DkYdHxw3QkZpU+LChniWJQ1XORLRDu5MfoW45wmjgdra8cubmbE6ByeNXFWUhvHE+5aHFu/VT9uhw0Yk0CyW6S5SXkXQfCR6vJNLnHg0e/d3ZQUtzGsfVzXDURf3g227l1Xf/RXOlf/qIlWo5jP8ZJF2qPFqAsmoXmloIeWLaXbvHzD/iP52czto56LoJsXp1hRQWrqbUrGs06KfLaQoDUSJADG6i2aDeAshswaBgJ41T8lMr+DgqM4vB4d3QwOs20wNplfJugLTFYZ5o8odZzrm7IvRnFwll6C6eEukdYFczHJmcqnWr3LHn6+38+Mf84FPbnhAs/d08xZtdTm+tT9sySkhrXxjETSdHJE4YmzcCFsPW9XoGutUjCalMjfuJe/po5QPsCq5Uk37qG9+UfegxLqT5msxfQefEIkA==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-secret
      namespace: '{{ .Release.Namespace }}'
    type: Opaque
---
