apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-secret
  namespace: '{{ .Release.Namespace }}'
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgAlnM9SaFLHVFBjjkn4gBQ2jyy/YTVrxy42eGbeBTa5Gtf2cTeArjA/0l+VlymV1l5imwAWw4u0/Fh3KlmNBxXK9okK4+Lenx1KIavNW/lme09Z2Xkmt7jeu3gf4+4oWwEbY+UYiRN+UHphiJVLCOwY9LI2f7jOf/Jsg6n0UOs7OME5zXm9ksbLWhbVHmoP5CGpDWy4sAm9DSC7OZnhM6zoi/FkFr2kC8QRk124sc3sStcoeg+YahujiY83vxCFY7LhHNqoNCVz+vUYTITnMUMjsLmK/PWUD4KpefMkeGGyZGlD+HY+yxnoe1bKekHjPVmLMIDifj702GhZP8Vq9z3ZLDN2CuCmBBY27uHHaIsyQk3p0MCvX6RLAWNlBpTIXshAFsusactktPWGpkEA//Xb8kmjJBjLy5vEuaqrN1hOGrMBenIc79yELRUpp2GGAMGdmRb8UrkSlzNn8Zg4REmBUgqbVUgN8Dsm7LP5QezpAhZlOBGCvXT5SYw1hAOOGmelOfPv/seRA21o6oeQQunf72Pkl0NuP2NgHpwwohG/7kGvgdjZRQ3rpvkZpSwK4gt/onm4T4laj7Cq6SpUk0B8hagE9XmFAMKC3MdDkNf+clbBl4xiqMdrWMIMplRIZOcdBGwz+zpIkXxtv0Q/HlDD/eDrUTvtE9URf0PGuO+B9omCMOwHAV9ezxVaSds1NVHVuoSIdGBh3w==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-secret
      namespace: '{{ .Release.Namespace }}'
    type: Opaque
---
