apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns
  namespace: '{{ .Release.Namespace }}'
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgBwaqHf2KwBueRdSmRE8FWJ+Dx4kjbyykMVbdme2yT/B8lFSmB3uLZEnbevNRmqmPh5VZBdj0qq8Uw5tFEjZUYHnJ0Muq+oF/C2BhEeHtO5c1fgkaOKcFNw9Igp0zKOs8ndmq6ti9KhmKb+ZrCIG/tr58Kwwp1nyXZTwz8L2fzhjzRm6b8L19HJ4WuA/UNB6hzBJJ53W42WmnWITKS1ena7S4zvv5Civ4rWv7x/4rfetskHC1zgvQLGpYQv8jfy4QpXQ5/sqHxQmxYIz9jsEaii3NfR+Fg75desvlu/AzseyqVBJncMIofwtHUus9vpRVQ+aTzEdvRIqtzKRNE/x4IwnFlDl94N9d4zYvlnVlJ+/GVWh9dSiCthLNYi9iz9jrr35RncCTxdIaxaf3FX4QBzMfrjocL0sx+dcRrELwE0FKDvfTNqAvtN0DtYXWfSjimNVq7Om+I96pKorou05rHAzXYxYQwhiVUEXg+DhZLDvAlUjRIKIdkNN5sB8dIrtMvIfwxJ2/AfHZ6XzJ4YDAl08v2h409+6qOIKk3xi+6QPnqnJHQYnpiVz4IR8Vf4W+zjy3RmTLUClSWQBEhTkrGzZf6wQKTamjHl3VIrrK1ZLqreHUK2PXiQwL3Px60nwWSusho8Op2h0lXncHTM5ZFmKafKoaufqB0MlEhg5wP7pRGX0GaPCbE+Pl4SpI1XG/mz5IbDLu0RVQ==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns
      namespace: '{{ .Release.Namespace }}'
    type: Opaque
---
