apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns
  namespace: default
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgB/Y7xu1O5GfMPNArKmewWrHSlqLhggwRJl6r6ZoenPx2jOwaIT+7ouXg/E315V4OHxrl/9fTo3jKICCj8oo8uCe/U6GXjINjz6LEsdgIO1fTDYZHERasjtXmRbVnQC5Bv8IGiHu/0OWHm80bCtmCmAHibNAIp2KbPZx5MwvvpAunUoDLQtWPxbZI4c3Iqx/JWZIONS+9jaV2jMv0OvG8rxOxLaSk6XDqFGMBn/54jO0/eEAtfKSVMVjx/G6r3ZfM/Y+TN658N0APlddiqb3GBzggHyFhqDit+iwbCwf848y4St1af32y4wDGUnnxPymfUCsV4BxiC+NoCpzR1xHf/FW+WaV6tK5NbaxUBnrSoENkeBnfeK4KCO6G9ZiyE4061pq8OQE048ECDK13HJ1Pq0kunNFOcGlpmKHHHAKuLJ6CFbAQYPIu4n8xcCZkh7ZPNQCyd0WkWl6eMatfHxzoZALirwLehzEbJBnw7pyaV+QMhrurPcW7fpRFhEvyPrg0QP8I2H8Kh+7dBsIK+UUz4o7Q+PTR/7GHb3Sv77qLIbryyQX7XpHmu0IzFiINkP1mTtx8M1eR0zfs0L7VSVBoYPj7UQFpvuZGoZOqSPt+VheeUF+OWYtZhyS5Aoo4rBYRv9INq/274JyTUx/+v0B01RHsPzFMod4PtGIrayGATdkoJ+8JzJqhGUl3+zsTSkS3DVr9SthkepwA==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns
      namespace: default
    type: Opaque
---
