apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns
  namespace: default
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgBSlO49XVAj+NUm8WQRbMdrvt4zJZtvE9T+2ZgCA5GLqBmoTapzgPbON9qSm8+LOr/QEOdeEFiZe5Yi+ZO3SWR4d+dgKLfxJIfk2WZjtnI+/xSJeszqmmJEuAOeepnjgSWwcUrtKRUxHZAGJWZ2rT+D22cUQ7g/4iVoMbaS+z5OSa/+FkY6ChLz4eaUJqez3Tz1W2EvRW0KvzboNZc+41MJsSqWRF8MX9Y2Zg2qYu0VYPnE0oK2KlQoZRCMGWWMBm1b5tPp8QWsSay05leU09g3/M/trtnvnLmpkGZX0FecnyuRCi4dxkPv+dpnA6vfhi5zHDh3OFhPxBsuD0tOtesks4jGiq9ZkOYmlCbUalfdEAiA8F+U/zkCcxzppzTb56rURLW83OrVTee+JaGFVUknlqdRUef2z4Mj8cqGBskX0tDBzSy9KoKPIYsx00b8hQDmx7u6DIpk2WO4gBsgEq2RqyvIt+NbtpbuiePsUjAjlexxeY5ucocMzizuQ6U33lAK0fppZ2pVwvpbmAEg6+DcSb0C5tNTTdR7dCEH7XFru+gUob6hATItDI/pBoUV0zDcFdkfStLeY0RjgvyoqDzgTi83T7zSTRZfe/6ZBziXmxiRKt5GNhcqrbKANIH6UnwdedpNgmvjZZgXw7VfZuJeV8np/0cy1m5orh4WtrLNa7OjdofzPMI8QMwn/2lrpxRMqL6Wy6e49WsS5dh7ft8=
  template:
    metadata:
      creationTimestamp: null
      name: external-dns
      namespace: default
    type: Opaque
---

