{
 "title": "Power Consumption",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   { "name": "tariff", "label": "Tariff (CHF/kWh)", "query": "0.2238" }
  ]
 },
 "panels": [
  {
   "title": "Power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"waid-bucket\")\n  |> range(start: date.sub(d: 5m, from: v.timeRangeStop), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_act_power\")\n  |> drop(columns: [\"host\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Home Total Power",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 21, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"waid-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"a_act_power\" or r[\"_field\"] == \"total_act_power\" or r[\"_field\"] == \"b_act_power\" or r[\"_field\"] == \"c_act_power\")\n  |> drop(columns: [\"host\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")"
    },
    { "target": [ "sun_altitude" ] },
    {
     "query": "from(bucket: \"waid-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solar\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power\")\n  |> filter(fn: (r) => r[\"channel\"] == \"0\")\n  |> drop(columns: [\"host\", \"channel\", \"serial\", \"topic\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")\n  "
    }
   ]
  },
  {
   "title": "Costs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyCHF" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"waid-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"a_act_power\" or r[\"_field\"] == \"b_act_power\" or r[\"_field\"] == \"c_act_power\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({r with _value: if r.a_act_power + r.b_act_power + r.c_act_power > 0.0\n      then r.a_act_power + r.b_act_power + r.c_act_power else 0.0 }))\n  |> drop(columns: [\"host\"])\n  |> aggregateWindow(\n       every: v.windowPeriod,\n       fn: (tables=<-, column) =>\n         tables\n           |> integral(unit: 1h)\n           |> map(fn: (r) => ({ r with _value: r._value / 1000.0 * ${tariff}}))\n           |> set(key: \"_measurement\", value: \"kWh\")\n     )\n  |> drop(columns: [\"host\"])\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Power (average)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "import \"date\"\n\nperiod = duration(v: uint(v: v.timeRangeStop) - uint(v: v.timeRangeStart))\n\nfrom(bucket: \"waid-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\" and r[\"_field\"] == \"total_act_power\")\n  |> drop(columns: [\"host\"])\n  |> aggregateWindow(every: period, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "import \"date\"\n\nfrom(bucket: \"waid-bucket-downsampled\")\n  |> range(start: date.sub(d: 7d, from: v.timeRangeStop), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy_daily\" and r[\"_field\"] == \"grid_net_kwh\")\n  |> mean()\n  |> map(fn: (r) => ({r with _value: r._value * 1000.0 / 24.0}))\n  |> yield(name: \"7d\")"
    },
    {
     "query": "import \"date\"\n\nfrom(bucket: \"waid-bucket-downsampled\")\n  |> range(start: date.sub(d: 30d, from: v.timeRangeStop), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy_daily\" and r[\"_field\"] == \"grid_net_kwh\")\n  |> mean()\n  |> map(fn: (r) => ({r with _value: r._value * 1000.0 / 24.0}))\n  |> yield(name: \"30d\")"
    },
    {
     "query": "import \"date\"\n\nfrom(bucket: \"waid-bucket-downsampled\")\n  |> range(start: date.sub(d: 90d, from: v.timeRangeStop), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy_daily\" and r[\"_field\"] == \"grid_net_kwh\")\n  |> mean()\n  |> map(fn: (r) => ({r with _value: r._value * 1000.0 / 24.0}))\n  |> yield(name: \"3mo\")"
    },
    {
     "query": "import \"date\"\n\nfrom(bucket: \"waid-bucket-downsampled\")\n  |> range(start: date.sub(d: 180d, from: v.timeRangeStop), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy_daily\" and r[\"_field\"] == \"grid_net_kwh\")\n  |> mean()\n  |> map(fn: (r) => ({r with _value: r._value * 1000.0 / 24.0}))\n  |> yield(name: \"6mo\")"
    }
   ]
  },
  {
   "title": "Total Consumption per Day",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"timezone\"\nimport \"date\"\noption location = timezone.location(name: \"Europe/Zurich\")\n\nstart = date.truncate(t: date.add(d: -30d, to: v.timeRangeStop), unit: 1d)\nstop  = date.truncate(t: date.add(d: 1d,   to: v.timeRangeStop), unit: 1d)\n\nfrom(bucket: \"waid-bucket-downsampled\")\n  |> range(start: start, stop: stop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy_daily\" and r[\"_field\"] == \"grid_import_kwh\")\n  |> map(fn: (r) => ({r with _field: \"Power Consumption\"}))\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Phase A",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"waid-bucket\")\n  |> range(start: date.sub(d: 5m, from: v.timeRangeStop), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"a_act_power\" or r[\"_field\"] == \"a_aprt_power\" or r[\"_field\"] == \"a_current\" or r[\"_field\"] == \"a_voltage\" or r[\"_field\"] == \"a_pf\")\n  |> drop(columns: [\"host\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Phase B",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"waid-bucket\")\n  |> range(start: date.sub(d: 5m, from: v.timeRangeStop), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"b_act_power\" or r[\"_field\"] == \"b_aprt_power\" or r[\"_field\"] == \"b_current\" or r[\"_field\"] == \"b_voltage\" or r[\"_field\"] == \"b_pf\")\n  |> drop(columns: [\"host\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Phase C",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"waid-bucket\")\n  |> range(start: date.sub(d: 5m, from: v.timeRangeStop), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"c_act_power\" or r[\"_field\"] == \"c_aprt_power\" or r[\"_field\"] == \"c_current\" or r[\"_field\"] == \"c_voltage\" or r[\"_field\"] == \"c_pf\")\n  |> drop(columns: [\"host\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Energy Import/Export",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"waid-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"a_act_power\" or r[\"_field\"] == \"b_act_power\" or r[\"_field\"] == \"c_act_power\" )\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\") \n  |> map(fn: (r) => ({r with _value: if r.a_act_power + r.b_act_power + r.c_act_power > 0.0 then r.a_act_power + r.b_act_power + r.c_act_power else 0.0 }))\n  |> drop(columns: [\"host\"])\n  |> aggregateWindow(\n       every: v.windowPeriod,\n       fn: (tables=<-, column) =>\n         tables\n           |> integral(unit: 1h)\n           |> map(fn: (r) => ({ r with _value: r._value / 1000.0}))\n           |> set(key: \"_measurement\", value: \"kWh\")\n     )\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"waid-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"a_act_power\" or r[\"_field\"] == \"b_act_power\" or r[\"_field\"] == \"c_act_power\" )\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\") \n  |> map(fn: (r) => ({r with _value: if r.a_act_power + r.b_act_power + r.c_act_power < 0.0 then r.a_act_power + r.b_act_power + r.c_act_power else 0.0 }))\n  |> drop(columns: [\"host\"])\n  |> aggregateWindow(\n       every: v.windowPeriod,\n       fn: (tables=<-, column) =>\n         tables\n           |> integral(unit: 1h)\n           |> map(fn: (r) => ({ r with _value: r._value / -1000.0}))\n           |> set(key: \"_measurement\", value: \"kWh\")\n     )\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Phase A",
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 31 },
   "options": {
    "content": "- 31F1 Kochherd\n- 36F1 WM / Tumbler\n- 51F1 Licht Steckdose Küche KS + DA\n- 56F1 Entrés, Bad, Küche, Wohnen\n- 57F1 Loggia\n- Balkonkraftwerk (inverter on Phase A)"
   }
  },
  {
   "title": "Phase B",
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 31 },
   "options": {
    "content": "- 31F4 Backofen\n- 51F4 RT MM-Verteiler\n- 56F4 Zimmer, Dusche"
   }
  },
  {
   "title": "Phase C",
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 31 },
   "options": {
    "content": "- 31F7 Steamer\n- 51F7 GWA\n- 56F7 Zimmer 1 + 2 (Büro + ...)"
   }
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"waid-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"c_voltage\" or r[\"_field\"] == \"a_voltage\" or r[\"_field\"] == \"b_voltage\")\n  |> drop(columns: [\"host\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}