apiVersion: v2
name: monitoring-system
version: 0.0.0
dependencies:
  - name: victoria-metrics-k8s-stack
    # renovate datasource=helm depName=victoria-metrics-k8s-stack registryUrl=https://victoriametrics.github.io/helm-charts
    version: 0.95.0
    repository: https://victoriametrics.github.io/helm-charts
  - name: prometheus-operator-crds
    # renovate datasource=helm depName=prometheus-operator-crds registryUrl=https://prometheus-community.github.io/helm-charts
    version: 32.0.1
    repository: https://prometheus-community.github.io/helm-charts
