fava:
  env:
    - name: BEANCOUNT_FILE
      value: '/bean/main.bean'
    - name: TZ
      value: Europe/Zurich
    - name: WATCHFILES_FORCE_POLLING
      value: true

  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: mekanics-ca-issuer
      hajimari.io/appName: Finances
      hajimari.io/icon: finance
      hajimari.io/group: Babsi
    hosts:
      - host: &host finance.bbi.mekanics.ch
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: finance-tls-certificate
        hosts:
          - *host

  volume:
    persistentVolumeClaim:
      claimName: nfs-fava-bbi

  priceUpdateJobs:
    enabled: true
    commitToGit: true
    jobs:
      - name: weekly
        schedule: '20 00 * * SAT'
        # schedule: '03 17 * * FRI' # 1h after the US market closes
        timezone: 'America/New_York'

      - name: last-day-of-month
        schedule: '03 4 1 * *' # Equivalent to 10pm in New York
        timezone: 'Europe/Zurich'

  resources:
    # limits:
    #   cpu: 500m
    #   memory: 500Mi
    requests:
      cpu: 250m
      memory: 250Mi
