ansible_become_pass: "{{ lookup('env', 'ANSIBLE_BECOME_PASSWORD') }}"
ansible_user: ansible
ansible_ssh_private_key_file: "{{ lookup('env', 'DEPLOY_SSH_KEY_FILE') }}"

deploy_account:
  user: ansible
  group: ansible
  sshKey: "{{ lookup('env', 'DEPLOY_SSH_KEY_FILE') }}"

bootstrap_account:
  user: "{{ lookup('env', 'BOOTSTRAP_USER') }}"
  uid: "{{ lookup('env', 'BOOTSTRAP_UID') }}"
  gid: "{{ lookup('env', 'BOOTSTRAP_GID') }}"
