apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-postgres-backup
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: {{ .Values.backup.nfs.size }}
  volumeName: nfs-postgres-backup
