---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pg-n8n-credentials
  namespace: postgres
spec:
  encryptedData:
    password: AgAxBiC/oct2kPHS4xiyiT2grzl9m6Tr3+KBlm2zCVS3xiBGNnpDqoxzlr4HFANpvC23YntoxxuVOR7FxxfH7izuR31jB0h0OHHcQNmHumGGjEiQMh9CO3Pi3/CQJrR9mMNipQXvL0JaD8l2JlsNw+Tnpt/sMmVt2ZBQTCtwowFQn1GhjN8JBA4/4b8eYnFdB3xK97kcEzDxPl7u6O7kmdw88VngNOzPvdsyfQOY1td2BvICNZkNGzxKrTi5n0FT4rHVreIj1/ZP8qv/FwyBQjtPF2zwaeDtLG9KuCp8T1xHfbBn/jbMRynQkzkEIIT8Qao+TuWH9QAYvf9x5NPHWdsG8SkFVAYPqfV/7K7PrVh0RcSN45QW41xGy+nVwpK0Ukvd9xy4gM+rIRkhnGxzYnkqHhWkSNgokAddn8Oxkg5oW6bXLBsBq/CXbFQgjfOdgeVFSkawU+3KSohH7H8N7sGW5SaFAKzmSwnvpC99X69q1MHQJPqWmKiXKRHQh9GMxGDQpqqhyoqJtUaVdFPGZu7rhZ3gYUAMd0omV8M/bqjY8PRxdFGwz1ygU5RlRGnGf23M+2ByAXnS7+gD3DRzc9FdNuLrkjEapqXedqhF7lxbObDpBWwfn/lSVASI8vL9kxoq+cAeLVladHmNHkSOOUYd4Zn0cQ2wMOPeIhdkWSglRkOz07azmHlvEa6QJkk5qg3zUdUY5mldcy06kjU8Iov2pGnf52+VNlkxnddIXOj3+A==
    username: AgCuV9I1DJltUzs7msMZ8GNkEFAf0fzmY+nTVFuYB+P04RKjzq9nWaVA8KSlqF2iy/zBN1oM6im2wXc5NywvIW6ZmCnsheE/72zLXn2PvD/ZimTg1fLj3WACGeRBPh2yDE9NP8OCWSLjq3j5vHEO+kZ1/FDoocyifQKI6Mrer73AXaCUXmMqYmccDXCYx0Qm5XoscwpYDHJBTEevtmAtqN02YVTIeQp2WJU+i7DnrXmLjnTFQAyE4DYXCEN3i/mWsV+h+iv0tPVogZxvjsYGlHgtn4mWYwRI2WDZYmHhuDgD1A52FfytoLCqLUMzsI82phuipQPIatW/YVPiV/WPjIDgWepQkaHND5188sU1SzKS83QcH7onrC37Ia83wyh2oOq4ntAmINnVtnZNdRW07KDFOma8cRklvdLPhrrL5ImQhxOBrU1uqnCgP475zQ6jjuyVIBCUPbRFMVwcoIgQHlEhP6u9n7trDNcjIvqFNempel9xhs7zZbJUHXIJaT6RmlXIfQoLRNkFgOFg9ASlGMLEisoQdV5YLG4yRrP+FCm7dCik9+eY7i2uiDshU1TOuK4XH8tc1AnVK78rgqqDsYSM49j3Q73OEExhKFW1r+1btsZoawqZsCXBCXXjD6+bwtzSqiCEf8WRvhfzB7qQKgeF2+AfrnUNwryOOakD+826wp6OyBcJgQ+z7nQic6ecR6qp0Y0=
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: n8n
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: n8n
      creationTimestamp: null
      name: pg-n8n-credentials
      namespace: postgres
    type: kubernetes.io/basic-auth
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pg-paperless-credentials
  namespace: postgres
spec:
  encryptedData:
    password: AgBBxitezfaD/PR5HLs6xqt+bSUtKs6Kjvp+Snmzvzu21ClpPtEtVAGWy6IE4ZY0Bql7Fg+S7SBzNmWeyODNW2gF3abciYK9PnErEY8I6Vpqg3fWam72BW/UiBWXvs4GST2YIWQ20Pz8DikoRgPEUBAvurZ4Lw3cJXU/frXoR+nR9UlVrLjTmrymy3PhMX+2wFCWsX70yYcWNrvFAxp+UN4/RVB3vF9wGWn5umeqRmTa36z8dN4YmFe/J+gUNKisWEYQS2QLix3nfetjBEbniFGmfcS9p9VR3p7Itfn40n6RNnykNbY+giqn3bFHkB5EJx1KMHDw740NdZW3WpFSvZuKYrO1hD1BbJHfTfEbAuZ2+2HwspNj6QqTmLFEnFoHmzVyJZIWxpetmHKYHWCjXqt6q+Sg2KV4AUlOBk3fdQuwrRRgHb/UZzPZK0KmxTnThPtyHbYKDUDD5t8ynfrqEfyCTmeM3/QKxNP70temYO7vjkrT4cHOuft8jj4sA3OtHnvMaEBGrTms3pmxYzqZJs2O//pm25Mzsi3XfJzKdq/kYuUCUaqWZn5UHtE9R3WXSkA3lnsaceWHOn8eSCPqBGshEGWoU/ApgSLmh6P6xBi4ioMIJF0iPeh45PWxLTBnriSKbQ0W9rUgKozJKviR/vFqIsJwa697TeorOYEWshQ6UeDcVg4CdKloJTm0p5Y+mjXyTrsYh9S4PD0oHUozVhX/NAYFxopAUf+bm2jcMciKiA==
    username: AgCNu7JXyXKtpNgvw/1P9A20+jjUd/IQNI6Dqr49byilNDtoGFjnICVFTQ2ZVe6+WxYpDOdipGOlEm+3qyKh3G8/ccrnBUUMgmcmNzN7GjAtSmPz4UuHiSIjJ3cmuoLxQmO3CY949UNQhjb1sWtdrroRCHR3FJ1LcO6/xOBKse0brPOJnAdWajiQQ9WGqWZ8Qp0dXkj3krt2WyVXUIixeZLOXdmirzKf+9nbg/kEvlmQRvguxiX6dj8+YO0/G2/ZX5Nuhns/RtE6904cERPiCh0l60LbTgofzsAozBpq36QPP8zb1eFwxHlptqvgQA0i5biDbrebrjUAPFTuz9+GMUoT1kcrshZYfmkOS/GNmGSQJKQuUd5TYF+1U8FIbSq3EauQpWXxv8xKZ2dQTeA9UKurxERQh40diL0quEx/Qu5o2aYy+k0DuYslVkOwOHDIgipLqw92/tFm0FcbQ0VTYf4Ystk0DkbLbRAth8c+z+igUMg8XGLSactU/YhNqq4BfcHN8MSqM3o6NQ7qLuaPhoZ5FzPcNxGq0M5vjXusIDMAFEPRpG133aNTaLu9RLWg+SMCYiVnifkpHHuJjaOEVitNiD6obiq2xnw4hA4cu4nukDwYIwtlI2N0qO2MPbJEpIRyZSsIO5JC3F5o0Uy7sSADXGtqLTZjX4OEgsc8jVdcvwCKXs/km5bwVYQ+LOxfantOae9QHIr3wJE=
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: paperless
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: paperless
      creationTimestamp: null
      name: pg-paperless-credentials
      namespace: postgres
    type: kubernetes.io/basic-auth
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pg-rag-obsidian-credentials
  namespace: postgres
spec:
  encryptedData:
    password: AgCdYkRD+6KYawlEh38FmDIkiLh0LV6F+WoUpYERprwIb3UDmiSgvKxz9XX0Fev7fA+Md/KYPSNmbkIouTGFYdKDYxFd948Um5fqNlTFxQeJm32kIifp5mVAijb+J4xreQUhVP+N5gmou7X7oaJ6ifl3OIiWYzGoLJ/IpGem7ZFQGECMOOrZnTQk0gaqi43A6+vqwEV+D9tRIgI82dABtwpKeZI4uHsoLfLXmpBFDMKxlMvOGEa7qHpJBL/fFprcWxfjpZnqpHR6ZFW6z/bmS5WUMW2YS/H9nyj3Rw5rBX0yyO28JXXO8G05SaoqMhkmrWUxvQy7Avk04pvJxV+FgwROo8FzRgvYYHHZ+GAW2dulPk8HHa8NPf8B1g3g9KxbvX3K5D9xeE1sfQ8zvD4m0sgUfBVl36b4/NgZZSC18nPoReSvNK/uuyzG1EW0rvaIHAgJNfbHdid0C7x8Ahd3CDPIxLevqQyU6W4PeC4Nu9tghk4pBs4xzBljDEnug33psIRTK4AsNboaMuhQpVS/dyFYtQPIBsPQgi64NgQNdwxJI1TXzGX7lQaEXIUSU687Ml90bMvNJR0AgL0Wpnwed2UK9pn2kj1Drek36+lxyud8cXdXii6xGC3HHfN/iT0i6aZ3ivLZoHx0TJ+MUWSEhXYSsXLoZu4F/DcQ4T9ws8/c6KpojaqXGHqfsMLuuFPR3Wzcc2Hoegvfxd0WrcL/RzfCsB2B3IX4G0aokn8J7rzgQw==
    username: AgAIDgh0oS2UwNs2gmp9wKVudrggqeKjjRqouCxznJZWL7ON15gc8rHwWFvMWJsa3y7RPodw9WRDbypvv+TI7S+lhb5zmMY1rg7N+vT/9fsTGAVBuBsNpFqOoDMC/S99mQffdsslBd074WgKWzcOEh7FFP9WoZnZ6r0IBD1JpY08/kkb9ilemE4UacIuJWS4vl3Dj/OcmKNLzVfUTJXou7UZBwM+HDr8/sevdf3/hjcfPteMpxKpZkMuzu0RAeBSgTRagiMnHGSn/4LvZ+R/RNLyCA/YP6EAqOM6oKiK/07Kjg5qOaRrvEscsIhGRlzzolFZAzrlEWrLRKuBN2NVsMXAv3xxzvgps/FGH7kszGudSbLAXO2K9Y5TbWyPsSrVIW+OcBo7Wem6r0tXR9a9pSr9KD1l17MIXQkQ4cY3hZkfR2x/AuhMxcBmkr42bhfoTIqwAv3muCOLOZ4WDfah7qGVHOaAn8reMm1Xoj07qTFFwM1VJFr5GbfaKqYSPjGmCcofcx+YjaAhpikxOkH8hEJg6/JLZN2P8QKUI9Uc534ougse9vDrUUEWb+tigM85bR2MbuySPt0kIZEl0YpSMdHop2lWw44nmnIyUPkH1EnIIJHIpZL9Mklyfh4jyy7iTrJ7FKc6YvmXhbGPjpRmT1lo9EewlxN7Ez3OxTihF2GAozC090Kul2jD0Lx4qanZ2fb+xp+C2JPcREaXP/0=
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "~"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "~"
      creationTimestamp: null
      name: pg-rag-obsidian-credentials
      namespace: postgres
    type: kubernetes.io/basic-auth
---
