apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pg-n8n-credentials
  namespace: postgres
spec:
  encryptedData:
    password: AgAh0oB70svhmJ5/ffHc1WJZYRUoP2dt1MmbXeMuZKVe1B+f/TrEeX6JUxYK8xzCREIzuSL+Ln7n7QN/6BOarBS5seH5oo4fypqP5zWkp5p8VFarCV985tuGM7+38FZkqLSlAnTawnlSxGtbSQsLhU4csaRM0a3u82/+d8k6xqzHn6mwtMOR6+MILrexy2zWGmEz59FB4CZTS2GNCViuxHOXPYKAJwxdrGP8XJJ83Oj+xq8gmt9VW0vi4WCVZX4/h75qEAEsEn0Zvsc8RKL304L+512f+aZCWiyXdnPXcdxvgdiGpENMctPNGfxIIWWpaCm98s7l7BSUZdJa2S2aDQKRwZOd0Hjga+Y4e1b4ERZWrzPPf8+lZiFxoMZwa9dh+p2FdWYz6xx5kUsllbmArH0KJKreISW+YaeV8Ruodq4l2mN2vKVj6sianN+t6xg0MUgnnRU440TYoAthQ14UVsqRsRJWOlkqz6tOTswm4Bh4A0Q8wb6cljj0cnNUkcd3SsBocS90ip1ZpG4zDifycnfJ4SyRkFi60pY97rKgtHhbRR7+UEdgE5yzU9SOhi0p65TpVZFtQD5VyHfSluw5Yu5yJxhz6R9gKdd1jJidUkOW1XZwG/iPzvzYq9YgA/N5cJeClRIy0hbb/W/6APKF11xbns8FTVa2znn2EGV0H0OT9dAcqcL5om+JOaHfd3glRWu3D6j3xJvo/RS0ZdTq8QsDypaVgS2T6/IdOrDd9mI=
    username: AgBpYdxIJyoWT89E8r1872+DSdP+H9twXRnBBa9ETLD1rgNpjBXHkBaZ4vOup37IK2nasBqO1xCH4D+21zVgk+SivN3g75Wy9Obyp+9mR5PJEORuTPGIRfvwTvefFDYFuulhFSOUTa3Sn+6Wb2Kx3W6Wr2O8rVUjwMPhjE4pvK/2rL51159ej6LvvUrBrfirg6alCXEGxJ+djF+nZ4pqdR4au3onm8njbN4swbd8z706WT8BguklOq6LlnqRPQU8XJuu2ZSMkVgE6P8xdE1POxbNbuJwNOe+IQbpTgHkyLxaHXMaYRI/7wP1/ZjYGFYx8HaibJzBp/Sia8DZ4Y67BpvQMB8Lv3Qg1E+p36Myav+emhotmvJUAuyaGc+M+8I3rBxOyvPTWOsci91+e6k8ox9QFKboG57mJ9cPRjjBvlofnZSGyiplq8NWzJaibEaCeWnLJBrHYSiOKuXY3W+TMRRiipTZwWyJty7hbq1u8kxYdGLiLv/kgIuU644lytJ+emT8FHZkC7YhE5fn31+P2yPZgMdXanAaHvxTZCiO5HC10sLSeG4Zs5pDq+8QB+aywFLYtkI+Cu3bfhmvyjWFRiIVIFCriXZ0CwrvFzoKkc7xzNay9yHPlGQ/oQFriSO/BsFzcpCUbY7tssmMjGp8jpbBz6TJtt7RIKQz1henOtkYiqJ9oAFNLzIkBzjcDiCfoOQlI/0=
  template:
    metadata:
      creationTimestamp: null
      name: pg-n8n-credentials
      namespace: postgres
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: 'n8n'
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: 'true'
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: 'n8n'
    type: kubernetes.io/basic-auth
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pg-paperless-credentials
  namespace: postgres
spec:
  encryptedData:
    password: AgBCyG+RzV7faVFhH62Ucqhw9J+PDsPTsxm1R5AEfbh/FlibFz2jJpj7kzjseGWxbn/17SM20kXfDd9fzrYg5qfsm24gkY7UEwlBZlFFC5GoOroekd3VHv0ldUp4z27fqxxGh2ZL6GVPiOHq9jXWt0PcaING9W4JvX8XsTylPyEeJSfwjavrmI8rBJXiMSE0zxrJxfsW/4ooMd30d4kTPqcFKOeVd9OpzM9mO8dORF4w+bxW03NYdhA8x4FT5Htr4Z46BFYyV13glk6fEVVW3z/m/nSPE4jE9Y7PfCypdK3yGDwgOMjhnONGhALKxehuUZ5WOhj5ABLRFETl3vthFcdjWos88qd1XWuGR63TiSD6+lub0NRq/jVif5WAmiPMrd+A8yk83/rl1chC5YDTtZ3eG9QAgkbDrEWNXiCaQvORbWlfNRgT9l2tIqX0ZJVj8MF8JGj/Bq/m6vcDyLtxi3AJEtIo+xc08oyu2edc1+3pm7+Igb0dR2+pDu/BvfmVeySzErUwEN+LHUOlSem/qcZLMsQ1kaHL50EaYdlkv02mHkFpugJDc0a2DuflbwZDZx7Zctl6ZSSUWXYoqphT0BLdaW4hITGuuqzy8RNWnZrwBV7y85ozcZI1PtaZGeEIzFwAZVfxrWrwViTEkUF/yt83f8EU0HPqTpr0MYoqQJQNY+zyyz/kxRPndly0ZCv+SRIURVZkqtt/T742vb5hTl73PWnGVuyl2azqhWTEu+4O
    username: AgAyP4VJmutroafPi0iRmTqNnniihJFgwZSB48xYuT5Ho4Hjn8i+mv2sbOlDeJS94v19qd74WOcRcna+YnlsKmBeCX+/vYXrJvGrPsDi64de8CVJpH5VZUXn/ov4+fofoyN4CVRs8oZwOpnLc3Fqi/1Obr6oA+fXEPqnULfHt8u4oe8b4gYkhe9XWkCr9zFmRMT0CTZgzg5/fWSSCqOahXKFdIGMITlHFfsdFCuXfOadGjdqTzDmDMGfyNUgjBavmAbOGbNdFew2Kh6HUzSI6iRW8mY1mDnWdWM89kR48sE3s16HQMyR7b00sng48NwQgg32stUqYP5VCWKomr2GeQ6Uzaxxb6ImMefH84ZWwJHn1gz1XVX0ZuDs9/KLIHOJtb1QtsaaLh9iLIRPHurFdblWOSK0NzxiGyZKO5QOYWsUkmtcJhBJ/NNfF1dgjxyqIGH6kWrhVJBbFGUML3nybabAtFD2O7tPFo/NIjUEP3fJYgjq0XZK+C+pxByENv72RNyx5fpF798Ew7dpm2mbU+dF390hUxSQ/X2eS44VhFt9ge0TAi1bUzfu3IiX5fTueDiQ/WC541M6mLkoNVDtCaNbwOtnQGWjkjN7wWdSgp/giRLcy+cL4eFP/49gMs5tsdytRhd8h89Uw7T2PnVXj6sn3PqjKmF+voW9o8Ar54iAFEQHwn4HkkkokPAdu9TrfwuJfXjA3CwXuhA=
  template:
    metadata:
      creationTimestamp: null
      name: pg-paperless-credentials
      namespace: postgres
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: 'paperless'
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: 'true'
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: 'paperless'
    type: kubernetes.io/basic-auth
---
