apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-monitoring-grafana
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  nfs:
    server: mercury.local
    path: '/volume1/homelab/grafana'
