apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rpi-alerts
  namespace: monitoring-system
  labels:
    release: kube-prometheus-stack
    app: kube-prometheus-stack
spec:
  groups:
    - name: apiserver
      rules:
        - alert: KubernetesAPIServerDown
          expr: up{job="apiserver-vip"} == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: 'Kubernetes API Server is down'
            description: 'The Kubernetes API server VIP (192.168.10.110:6443) has been unreachable for more than 5 minutes.'
