apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rpi-alerts
  namespace: monitoring-system
  labels:
    release: kube-prometheus-stack
    app: kube-prometheus-stack
spec:
  groups:
  - name: rpi
    rules:
    - alert: RaspberryPiHighTemperature
      expr: rpi_core_temp_celsius > 75
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Raspberry Pi high temperature ({{ $value }}°C)"
        description: "Raspberry Pi {{ $labels.instance }} has been running at {{ $value }}°C for more than 5 minutes."

    - alert: RaspberryPiUnderVoltage
      expr: rpi_voltage_under_voltage_total - rpi_voltage_under_voltage_total offset 10m > 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Raspberry Pi under-voltage detected"
        description: "Raspberry Pi {{ $labels.instance }} is experiencing under-voltage conditions."

    - alert: RaspberryPiThrottling
      expr: rpi_throttling_state > 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Raspberry Pi throttling active"
        description: "Raspberry Pi {{ $labels.instance }} is currently being throttled due to power/thermal issues."

    - alert: RaspberryPiFrequencyCapped
      expr: rpi_frequency_limit > 0
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "Raspberry Pi frequency capped"
        description: "Raspberry Pi {{ $labels.instance }} CPU frequency is being limited."

  - name: apiserver
    rules:
    - alert: KubernetesAPIServerDown
      expr: up{job="apiserver-vip"} == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Kubernetes API Server is down"
        description: "The Kubernetes API server VIP (192.168.10.100:6443) has been unreachable for more than 5 minutes."
