apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mcp-bring-secrets
  namespace: mcp-bring
spec:
  encryptedData:
    BRING_EMAIL: AgCVMkK+hFsdBFyj/8NKYLclizl77d8UyntifuX0Cxg4CFBqobyN8iZC7yua/Ge+h/GectpKUJDKl0WYf6JN+VIozTuZ1Cs4BVbsVfBghf/VJ/Gyw1bV6u6WCuypgZEvipHeHxiId2FIy5EfEWOsrZoVS+CRWANMhgqDd12hAvywlqUlAPxE667NPCuEgIdPue4cS9xer8+s9wpb7ucGBqWWV4lW8ViC34AFZqlBpalK0ChQpDgAV0U5GGnYbJDGRHU6ztyTrVG8lSF/EVXN2oHEyUHKRqBt0ZrA9oeWs8gvWHZtefWpzi7nZRgGvVpzcWgLfe3vzVBWOUg35zwobOb/E/4YqQi3MJrcpIMrkAIHg9ADODCUT3QX5oG4tJEXD9T66Pjtep6wfzyu05Pvz3j3eivMkPP8o0CWcFQgzRwY3WxUkc6y8vPlf+qyl7tC6nE1LPt0cIJn1h1QAs2VTv/+FFkoP9eOnJQEqHYw0NzjpVMSX6cDz1I1tWSCYiUJvp+XZiDXuF0UuqYEoa4sb6fnFxWklq7zv1jb/VExBGKVn2Da4YcVQa8bINTfZl0qf3EM+Q8a6Me/50/aS0cwMF24IXY9+Qulotv8FbOAjEhPh+RtcSiUYEc2Az9cju6Cv7+PZoyabs65mGJxJcvqqnHGJEIabcLsxIIhNjREf/OqqRC2VIrmhW9LOzUExG45qB6r5ZCEOWoQnzE5fjFSt8wfqB/UZyJ4k2mezQ==
    BRING_PASSWORD: AgBt6QMg6byo9+y2algZrd2SlO67NP3uPkGPJzWOyNfV2+0RsGqZfU74UrMqKWWmO2iF7YHOhHaGBG+bvkyhqV+kx3bdCO514722SZFkHUhN19hJi7FAy8J5HFtQqnqV3v6ZptcZpbrj2IHiMAv+PXXnB9eWyGMu/+faYr4f7SdZQmn15ZZQCNJGyXrGrLk7BR9vC6qwUDzQ5YASDdPVFGMpksYTyFQlfBJmRxZqDtKDBzZbITNRyg7F+JLsMibDGHAbYsLFj2KvpfRKjY2prNN+04SOUBkboao0q6L70G/Oz8t/QyPURKWN9QEMSB5gSBiRb01clcCK6AMjzk3Gy0I1SgoR4F66h09G7CXFcxD81PbZNRzvtQ1Cie8xW/Pd6m6raKraHOrVRumntcoaqrQo2jT1aVFI7D8kFUbEmEsy915uqtmguALNdd3oZzYZm30tY9nYkW+Lf6bvezoSQYLfAnPN2vOBj60/fmLHYfFFOXs7se3fEo0MEO1b25HStbLr5SA+Tzhi7mSBYaaTAQ/PeO1w4uSCa7TnaYIpzJV2f0QshKWdFyU7xs0nPr7GHVQ4mQDdGMFKfPv0xI+z1x+wEEYRjeqO27k3gwGsWqiXBIoMd9RX0elYqpw8jHDb0cyrfbFH9VLthgGoq1BmohCNQYU7YWqi+0yyVAHY3M8yx963ieY1TCOlDFnS1MT1HDDt8DDsuOeITD1l8cnReiRvxqO9G2U=
  template:
    metadata:
      creationTimestamp: null
      name: mcp-bring-secrets
      namespace: mcp-bring
    type: Opaque
---
