apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mcp-bring-secrets
  namespace: mcp-bring
spec:
  encryptedData:
    BRING_EMAIL: PLACEHOLDER
    BRING_PASSWORD: PLACEHOLDER
  template:
    metadata:
      creationTimestamp: null
      name: mcp-bring-secrets
      namespace: mcp-bring
    type: Opaque
---
