apiVersion: v1
kind: Secret
metadata:
    name: grafana-datasources
    labels:
        grafana_datasource: '1' # default value for: sidecar.datasources.label

stringData:
    influxdb.yaml: |-
        apiVersion: 1
        datasources:
          - name: InfluxDB
            type: influxdb
            url: http://influx-influxdb2.influx.svc
            access: proxy
            editable: true
            jsonData:
              organization: waid
              defaultBucket: waid-bucket
              httpMode: POST
              version: Flux
            secureJsonData:
              token: ${INFLUX_TOKEN}
