apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
    name: grafanadatasource-influxdb
spec:
    valuesFrom:
        - targetPath: 'secureJsonData.password'
          valueFrom:
              secretKeyRef:
                  name: influxdb-auth
                  key: admin-token
    instanceSelector:
        matchLabels:
            dashboards: 'grafana'
    datasource:
        name: InfluxDB
        type: influxdb
        url: http://influx-influxdb2.influx.svc
        access: proxy
        editable: true
        jsonData:
            organization: waid
            defaultBucket: waid-bucket
            httpMode: POST
            version: Flux
        secureJsonData:
            token: ${INFLUX_TOKEN}
