apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-influxdb
  labels:
    grafana_datasource: "1"
data:
  influx-datasource.yaml: |-
    # config file version
    apiVersion: 1
    datasources:
      - name: InfluxDB
        type: influxdb
        url: http://influx-influxdb2.influx.svc
        access: proxy
        isDefault: false
        editable: true
        jsonData:
          organization: waid
          defaultBucket: waid-bucket
          httpMode: POST
          version: Flux
        secureJsonData:
          token: ${INFLUX_TOKEN}