apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: influxdb-auth
  namespace: influx
spec:
  encryptedData:
    admin-password: AgAfTnF8fBvUXuiyVRsVSlNNf5Ox+EBD6Cg+VV3JAxh8fQ9CvkP/V6ifdk0Czn5VHMiOZgpf3UVxpAqAS/ZC4gZtm1a+Be84L+Vw9K72Woq9ihYRhDYlwgy1PLNVJwFUe8gwBSlUwONXQpMxGBgWDSDfb/xhleLa0dpL62oN7hXvyD8IIuB4/E4D2i7NOCa+yzOsh6G/f12qHh05DuIMfQQSEi1cbBRKDJ3e0SLVvX3O2uo0eT0sD66zkVHwZxFjSFfsC0N4UQiZLjU2e+b0SkoyKbVKjo6O7YwOAhEdXrIsr8hZHg2q42eLx25WO0n2dpHG3t8AJtAr/cZPVpoigfZM9IpKPGx3ig5CwNMOc/U311ObaFOMPzfa/3hjl+f7n5U1l+bj2sC92HA17sEvfEtRLq+aiSftbRP9/Dz/HEDY+/ffAil8cvVg+Gzs1m7lE5jPSPYYHIBU7NW2y0cQyOGpn/4rwXKJiw6FFA9poNoWqrYK7yPBltWlqKjh8QS8lISOCLVUT2XKWLEGKsmHCBZQ+a5Oi78g4TDx8YlFIysJcmQKmcc7rECtQs72uoTdFJN/yKNiivRE7fBi+vwzE/Xt3oJVQIY8imQDenReGjmu1Yv8YKAoDKE60L6ekEENoD1v6sNarYLn5WBVriv7dUmt7MkZBHEgQMRUKi1Nbuu1znprtMErUCsEwzX8pX9rk4h6xcmzIeG/qBYU2LU+lfZygFMoyg==
    admin-token: AgCWmygFWYlpEZ6LrgyrYMdB6wXRF2LQXiClsRUWEtLvjFolvJFm6eE01kNrq8j3/yv24na/Ct2NFhl2x9wgao2tGUaEbUuv6uS+TnhyoyL+fscTIBljkWHl2ZgkeWPlD5SJHdRllu4gWzCYcYi+lCMcaFBzavZdLLlRgcmy08fISPq7WrlB6/p9OcMN1mpYZaafFR5UWiPVxVIDaKDeo9mBg3Ibs2ygI25GW2ulAss5vmlEWpobU1Jtq8UZYC1ASzD+b9B22ryias5RjrWH18pDGiFw4Wqqmvw2VneDXSQwAYGt/EAEZ6RgtOFtEgB6ckq7MfeMp4nlvCIbjWIaROVacd51Ek6t5hTG1VCOowOiFO2fYc1gdAiULEcqrPglcXLzCInbtjf7es2wY3KhHUrS2i8pVjOaZUeUoByEB3alEBQZCr4C4aHg9NsLC3VuV89Qt+cSpVRWGx8R7lTV8uvdNSGUs6FR4Zz/3bEjk76ZwpdMTCUc/sCp5nZdSgoALmqQ7wQaHFmLlsKT0OU3I7N12hI/nQQm9yK4rmZP01HEyU6tk85gbgTe/+D1XcUhdbqAe0WbQZj+IiGdEUtW/40w71bQj2KwE5QJRDYoZs135sBLi4mK9Nfz4r2ZiQh396PahZVMaPX3VzYVxOrQe2VzhEB2jdQmMZBZd+tDcHDIpHR5lrCWYt5DW6tiPZJx2ugP7iUgbtmsxa9IS6pUNbuOrGZi0y8Tm9EZ5JPaZFU+PETC6Zx/4rcE/pg7ue1EeBOsujGUXzBvbp5HhZE9H7/fBrqNmB8j5lkJiPK77+reGT0V4ufZVxn9
  template:
    metadata:
      creationTimestamp: null
      name: influxdb-auth
      namespace: influx
---
