apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: influxdb-auth
  namespace: influx
spec:
  encryptedData:
    admin-password: AgDhxYcMXCzNo7u8VW31+STSVdX2dgpVYipNirrrYEuZxLKqTeMh6vqz6NdxFfMeu7bm2S55OwxD5dAl2e5WnJEJ3/354GXZnF81jIQ9q/ssismKbG6bI0iUAGwxtMyXLDnjIFOt9sQM2Ush6R5wp1DW/bFY0NFw2pBGihnekVBq9HDrWiK4niRpQSTVhKPETht/EGbcnUliXXGKb7j7ymKen6nB2OrARQ56tQSk1SGdz8bzGlQjNDkihpA3DlDxEsWtEnS7LAGgq49uAgj75CdgbLpqbkdBB8LSPIt5lGzmW0t//hIcz7TjP7FErgoOBJc1meKCa2iKOGNs0uHAZJv5lbZj5j2fnEkD9Ys4DD+VwGZjxU3Nj+arWEiOzYLAnm2zh0FmzCubra0MnWoKrAteX8PVBrxsUlfMAZTwJbw+eiRjRen6HSj19eaWG8WM9aIh4YcLCdUIBnT2y0C9QGQgx4aT6tJJ9aHpDajxfU40GV3ewxi4vj+KC9TxMKN2Ay3r7YPFh2J6J5hbw58pcxOJOl6v2PEewHNAXHH6FtOKIPeEaDAKzPBRlLFXKSUmadOV8S2vsV5al+4eqvzxK6f6DrgX8Z7efMjrSngkVPp30s4l0nGs76FXl0j/CXJrgOkWXGMQUuQxFn4FMDVEPEjizkanfZ8+rCKRlYfsLZHIZiEchsZL3W8ISGYOMz3X9SPZLUAYetmw9hPWngD7XJPmo637Nw==
    admin-token: AgAwWd4ICSmHGVRKMwa6wFbs8foaulcNuViCXZtX+mLfxzT51X22IQgTA65EguQIQkjK9pzWzTjkmrJOz/DGhAfLtl3g17QV4t8hm+uFF+brhZ6x+/PK7A5XYc5sLJXUsFbvIXGOGeVlgAHATe1lNpzseGwmXR5YNE/bO7ymU6kqVnQNrXsaMgvOCcHhOpbPHfv9uWfu62wc7kNlgRLPFjVEoE74iDiRVtHI0Ab54eaxvlkVH8I71Y7l3WqBXoz6/O43/GpYI3O1cZfctNsVjz1jnPzTXM3kfoQJATm4d+zLvher4IdTWJL47JPdcPX1OKbvkyzUW0g/eWxNd39MD8qD6RMQNndL6WQD24rTf48ilMPXeMAtFFCFvWVNzEl0bZOpDkk7UCARNE4FE77paDHc2hh9h9AeeBbCkeMwlt5TMpp6TTz8bLvuuKvD6qkB+Cp7FAh9gdEqzagFBWhigwIyqK/CZTpDUM/ZaG1qf+lCwGjODKE8HegHZwSui4WVPxAUQw+H49rgqQ5mMgWd/HexyIsveFejDPUh7BQWgrXeip+x5r++AI3VktPdrVWxaOUlQ1GJWLoYid7VEVImeB+Y9tEDfYddtG4SdVrx6wavpN7aTFhkbZ9W7/05w+8Ei59K1EfKGnJhn45hycQkhAeBB7AOrY+HgkomiDLT2a3szGubpIbsTB8uAlI1ERBT9LoejUPxQ0uG5xksIXuk4Fk3wFwyJaHsLIeRpAF7GDHCIjiACvPJDbGMhJwt7lCVbhY=
  template:
    metadata:
      creationTimestamp: null
      name: influxdb-auth
      namespace: influx
---
