apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-n8n
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 10Gi
  volumeName: nfs-n8n
