apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-n8n
  labels:
    app: n8n
    storage.type: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - nfsvers=4.1
    - proto=tcp
    - hard
    - intr
    - rsize=1048576
    - wsize=1048576
    - timeo=600
    - retrans=2
  nfs:
    server: mercury.local
    path: /volume1/homelab/n8n
