mcp-server:
  image:
    repository: ghcr.io/mekanics/mcp-plex
    tag: 0.1.0

  mcp:
    port: 3000
    transport: streamable-http

  existingSecret: mcp-plex-secrets

  env:
    - name: LOG_LEVEL
      value: WARNING

  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: mekanics-ca-issuer
      hajimari.io/group: AI
      hajimari.io/appName: MCP Plex
      hajimari.io/icon: plex
      nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    hosts:
      - host: &host mcp-plex.mekanics.ch
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: mcp-plex-tls-certificate
        hosts:
          - *host

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi
      cpu: 250m

  probes:
    startup:
      enabled: true
    liveness:
      enabled: true
    readiness:
      enabled: true
