---
- name: K3S server service started
  service:
    name: 'k3s'
    state: started

- name: K3S agent service started
  service:
    name: 'k3s-agent'
    state: started

- name: Reboot
  reboot:
    post_reboot_delay: 10
    reboot_timeout: 300
  register: reboot_status
