---
- name: K3S server service started
  service:
    name: "k3s"
    state: started

- name: K3S worker service started
  service:
    name: "k3s-agent"
    state: started

- name: Reboot
  reboot:
    reboot_timeout: 3600
  register: reboot_status
