# https://github.com/k8s-at-home/charts/blob/master/charts/stable/mosquitto/values.yaml

mosquitto:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        # cert-manager.io/cluster-issuer: mekanics-ca-issuer
        hajimari.io/group: Apps
        hajimari.io/enable: 'false'
      hosts:
        - host: &host mosquitto.mekanics.ch
          paths:
            - path: /
              pathType: Prefix
      # tls:
      #   - secretName: mosquitto-tls-certificate
      #     hosts:
      #       - *host

  # persistence:
  #   data:
  #     enabled: true
  #     storageClass: longhorn
