apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openclaw-secrets
  namespace: openclaw
spec:
  encryptedData:
    PLEX_SERVER: AgAVL/W2FLSkr1aAJxXE33MbMqYvJno1yE8A3RWX6SXpCJw+cjhCp2vxh7JeREJNRyKBcFs+GXxcSPpTXGDVL6VdTiL0RwvNzy+deDQPQydj3qguTTDoadcqY6Xd++K38qj8TCsojSDR6RPQIxLWIKABwhEO7rN02V4/uoL4PBRF+OOYIONVi4A8iogRAoWlDh0ZJEkC3iMyzLOAMdyz9NJ/PO5Dn8CAW2KDkKanOWtQLy0kFr1h1LNb3Jh9l7BgMb0K2emSTR3JLqwPjDY2kCmOrcgV8b/G2ASo0cjKuP79Nlu/n/AYN6po7HjvrucPH4YxtYz34IfPIN2VxzDE8tUMmVoMHGB3teZUfSOEQgBtT4Ur3o68nLEnfEpPs0MnV5QjEZgAkbMOlXg6LSBjcjKuDEaX64NTGkfZ9Pw8WgOeaO1MN4XShQNc7s3BQaFuHzE0mb3oyzdOimWyaILKwzMyd7WSR5sAF892bCj0iRaQy4KMr4vaBLoPiSnqY900h7mD/C9wXE3dIZ8KcQNU97OatTPqtSb9nktcU1Ic/7hm1GqBPzVMEW/BhWMWmcYDuwwXQhypPsR5V6qi11ShjmzjLtKqD/l4+sqASK8CkHfZgC6PV+wWNq7T4WsNcMdyzd6FH5W0npZ2/ECXdS9MMCxs+N2S8GsjX/GE8Zn8r1RnDTGh3LgEZNE/yZeAW4yPo7vGgEOMucYa0/d5kbOBpgBEHz+GqmBffEw=
    PLEX_TOKEN: AgBxWKtDrNHWxd0IYSjHl7PtngmG8tx2+35y0cL9vfnHLUeDCgWlyD3nHD2eOSCIRd7xJNHelcT152wIcZXOYxaQ2rXkwAiFi8Ln42Xqh5UILz1uwmlt1JgxZ/EDK45IHKyxogQxsy54U3sN7uQly5WvnYoPl959VcJsY5DBbROLJoBjwVoomrko4iRduJLhG4WjYYYtycdqBcedoB59vnXGaXMDYl334b9YiupBxRGPMxi+iyJju2FP8yiRYmrjFJpfdjgNs4BsMtV9U46OnH7mdd3hDVq2Ps+1Es4UESPjd/u2oyLu5jJLcSG+n1Osi8x3C4Tj6rVKJSw4LzF6d61UvjE1gQElyXgn8NX/ACzrO5xCaMFlREgcFPTxJGQGanDwfklGj6k4WKSol6SUWjScOam9U5IJp0K0woZ+KuH5FEiHUqpseU50hlznm1JrQpXocjx/3bFX+acfgHH/SsPn5QVda62YObPtvX/KN+nG7a2rwV2/CDw0S4PAIilt1ML7qFO95TeiRGsj5mHn7MvEWWJZH10PQg6LBSYNUE5V1KclU78k7SvOpiEyzgCGXGrNoc6D6CdvNTw16v1hC7lFiySUweqQqFNOm0XGYjSkzFQexoSnEzUTh9bDtsa0fxkjPuszpMGgfqKlSe6dJxV6uaLaziayuTH5If5JnhyQyQQBtwJ0G1FlAmwQT+QXsLbLNMnDCJ1RlmP4q8pwxiUbI3wP/A==
  template:
    metadata:
      creationTimestamp: null
      name: openclaw-secrets
      namespace: openclaw
    type: Opaque
---
