apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mcp-plex-secrets
  namespace: mcp-plex
spec:
  encryptedData:
    PLEX_SERVER: AgBoYKNG2H/xO7vHG+crn1fjzwpdg+9sRYgX5kTSi9ZxExQP5jviRTWlVysycqKFYIOAXWObJ1RLQfG6neyG4l+GP44c4LMcKC1C9VOdnDQ1cK0eLFBGY3Zu7IX/wrX95o+UjcVTI0ll3B8fSkxJIneSLmv/Xvm6RQIV/6/WdWxPIKLnm4P2ofp0cQwRWmsZQ2ayRNi7kxlpiL3z/SK5uwzRw8razF/dF+RqMvOKhfwey9Q+nKLfrQwb0i4sBUTRMruHNcR+ESd+LU6jQ22XkJ045ukzJEFU42o63M5q/K4Q5Sh3oFQKUL8golHzEHq2R7KPnkEzlLhlZqbsGZ/+LAdpWHzbV/6d8RK+B7V0SnlZcylN2mtfb9Y9jfiT3OBOJsMPe8iJn5dvwSZAWthvjOjiQ6o3QciO0L1kB25Y6qksRiRw2a+hCaJHMx8yhIiS1HCmQAcqkWIOHI27BT9kksb6+gi/35xe/qyiGdKhW0MVb49kfvxL3nU3eOTNuL3USUPZJRc3wXO1rbzjWnUw2wLk8H1AVKvPzbpWJoihiu00ZdoWsM/obMVCi0Khdou8qC3qkS+5tCDhhZG2IqZsnPv9weaQqpzJBEth4QLmVHWlDDfUHHOjYZ29n9ddVTnnxjvu07er7BYssHm801uzaWjLRyxITsFbvvB8ltXBQ1Sy0kmIY8Cb6+TsjrQx89B3SqoZzuvg+DP9o+tb1FeKLqI4UhGyDsB9/kY=
    PLEX_TOKEN: AgBtgJ1RydbHPxZarhc+q9ozROK3HuvSeFcupIc0afzgBS7r6GV/uNf7Rtx68pdSIF9v3Iicab4GPhoKSdiHRFg/JIgvYixe/cfqzNdumTe0eKBdZx9mJBi6pPu72w97vqxSiDQyxnav1hYkKqCWbb/YmtWCuVVKpCk0ndsyJolUEmROeSJtCixQq2t7rfL2mhdgkqVjo5PlTh+cgRaGlUpn3g78iQmFDmVRcKSbcIHDn2s95+pgkRHu4ZKEhAmcHyzm5giNjr5EHikuf+fpc9lSh7ekdvppFksvh8EFF3DDhCdimPuymovbovYXFX5YwzRacatHJvgKUbRAF61hTWoQxDd2t+SsWLG/dFdBPEfFzJqJ/SWZ3tlY0wdvEIKGE4jdPVcFCHwsp+5H6kZ3DPJx6xpx5i3chAZNrsJxPO2PLE9NJzjUf1V1rf+hy6g8rTKC2V3Ht1YmfgKOG0N4K9ip1c1o0suTb63dtgQb/esHkf3aywAnmQoVNV7MfpDjKSLD4g02gm1DJ4sARg3aH83T19Vz+h+GMDg+IeLmlKEHRpQj66s5wE3vmZ+KGQLAHaV/Q18HowMKuXz/pP2avapNCcsaXReZaHjKGUuvv99/xEAm7rfdvxeX+iTGFkKyQEMAuzhuTh0/nrVmS4wR/xg3U72q/wL4vVnMLWJ6dpt4NlBoOm764gKEIgmX57L74c9NAJThmGXFj0MftPtBNY9/la7yRg==
  template:
    metadata:
      creationTimestamp: null
      name: mcp-plex-secrets
      namespace: mcp-plex
    type: Opaque
---
