# https://github.com/kubernetes-sigs/descheduler/blob/master/charts/descheduler/values.yaml

descheduler:
  timeZone: Europe/Zurich

  deschedulerPolicy:
    strategies:
      # Spreads replicas
      RemoveDuplicates:
        enabled: false

      RemovePodsViolatingNodeTaints:
        enabled: true

      RemovePodsViolatingNodeAffinity:
        enabled: true
        params:
          nodeAffinityType:
            - requiredDuringSchedulingIgnoredDuringExecution

      RemovePodsViolatingInterPodAntiAffinity:
        enabled: true

      LowNodeUtilization:
        enabled: true
