apiVersion: batch/v1
kind: CronJob
metadata:
    creationTimestamp: null
    name: weekly-price-update
spec:
    schedule: '*/10 * * * *'
    concurrencyPolicy: Forbid
    suspend: false
    successfulJobsHistoryLimit: 3
    failedJobsHistoryLimit: 1
    jobTemplate:
        spec:
            template:
                spec:
                    containers:
                        - name: weekly-price-update
                          image: 'ghcr.io/mekanics/fava:0.0.4'
                          imagePullPolicy: IfNotPresent
                          command:
                              - /bin/sh
                              - -c
                              - >
                                  bean-price -d $(date -u +%Y-%m-%dT%H:%M:%S) --no-cache --clobber /bean/main.bean >> /bean/prices/auto.bean
                          volumeMounts:
                              - name: bean-volume
                                mountPath: /bean
                    volumes:
                        - name: bean-volume
                          persistentVolumeClaim:
                              claimName: nfs-fava-ajo
                    restartPolicy: OnFailure
