apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nfs-fava-ajo
spec:
    accessModes:
        - ReadWriteMany
    storageClassName: nfs-fava-ajo
    resources:
        requests:
            storage: 500Mi
