apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-fava-ajo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  mountOptions:
    # https://docs.aws.amazon.com/efs/latest/ug/mounting-fs-nfs-mount-settings.html
    - noresvport
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
    - _netdev
    # - rw
    # - nolock
    # - tcp
    # - async
    # - noatime
    # - intr
  nfs:
    server: mercury.local
    path: '/volume1/homelab/finance.ajo'
