apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-fava-ajo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  mountOptions:
    - rw
    - nolock
    - rsize=8192
    - wsize=8192
    - tcp
    - async
    - noatime
  nfs:
    server: mercury.local
    path: '/volume1/homelab/finance.ajo'
