# https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/charts/ingress-nginx/values.yaml

ingress-nginx:
  controller:
    admissionWebhooks:
      certManager:
        enabled: true
      timeoutSeconds: 30
    resources:
      requests:
        memory: 128Mi
      limits:
        memory: 256Mi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  tcp:
    1883: mosquitto/mosquitto:1883
    5432: postgres/postgres-cluster-rw:5432
