# https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/charts/ingress-nginx/values.yaml

ingress-nginx:
  controller:
    admissionWebhooks:
      certManager:
        enabled: true
      timeoutSeconds: 30
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  tcp:
    1883: mosquitto/mosquitto:1883
