apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup-every-8h
  namespace: longhorn-system
spec:
  cron: '0 */8 * * *'
  task: 'backup'
  groups:
    - default-backup
  retain: 3
  concurrency: 1
