apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: snapshot-cleanup-weekly
  namespace: longhorn-system
spec:
  cron: '0 3 * * 0'
  task: 'snapshot-cleanup'
  groups:
    - default
  retain: 1
  concurrency: 2
filesystem-trim