apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup-weekly
  namespace: longhorn-system
spec:
  cron: '45 23 * * SUN'
  task: 'backup'
  groups:
    - default-backup
  retain: 2
  concurrency: 1
