apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: snapshot-hourly
  namespace: longhorn-system
spec:
  cron: '0 * * * *'
  task: 'snapshot'
  groups:
    - default-backup
  retain: 1
  concurrency: 2
