apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-12h
  namespace: longhorn-system
spec:
  cron: '0 */12 * * *'
  task: 'snapshot'
  groups:
    - default-backup
  retain: 3
  concurrency: 2
