apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup-monthly
  namespace: longhorn-system
spec:
  cron: '30 23 1 * *'
  task: 'backup'
  groups:
    - default-backup
  retain: 1
  concurrency: 1
