apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
spec:
  addresses:
    - 192.168.10.230-192.168.10.240
  autoAssign: true
  avoidBuggyIPs: true
