---
- name: Reboot cluster servers staggered
  hosts: servers
  become: true
  gather_facts: true
  serial: 1
  tasks:
    - name: Reboot
      ansible.builtin.reboot:
        test_command: kubectl get nodes

- name: Reboot cluster workers staggered
  hosts: workers
  become: true
  gather_facts: true
  serial: 1
  tasks:
    - name: Reboot
      ansible.builtin.reboot:
