---
- name: Reboot cluster servers staggered
  hosts: servers
  become: true
  gather_facts: true
  serial: 1
  tasks:
    - name: Reboot
      ansible.builtin.reboot:
        reboot_timeout: 300
        test_command: kubectl get nodes

- name: Reboot cluster agents staggered
  hosts: agents
  become: true
  gather_facts: true
  serial: 1
  tasks:
    - name: Reboot
      ansible.builtin.reboot:
        reboot_timeout: 300
