# Tears down the k3s cluster. Don't do this except when destroying the cluster.
---
- name: Teardown k3s cluster
  hosts: agents
  gather_facts: false
  tasks:
    - name: Run {{ k3s_agent_uninstall }}
      command: '{{ k3s_agent_uninstall }}'
      args:
        removes: '{{ k3s_agent_path }}'
  tags:
    - k3s
    - cleanup

- name: Teardown k3s servers
  hosts: servers
  gather_facts: false
  tasks:
    - name: Run {{ k3s_agent_uninstall }}
      command: '{{ k3s_agent_uninstall }}'
      args:
        removes: '{{ k3s_agent_path }}'
  post_tasks:
    - name: Remove kubeconfig
      delegate_to: localhost
      file:
        path: '{{ kubeconfig_localPath }}'
        state: absent
  tags:
    - k3s
    - cleanup

- name: Reboot all nodes
  hosts: cluster
  become: true
  tasks:
    - name: Reboot
      reboot:
        reboot_timeout: 3600
