apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: homelab-dev
# image: docker.io/rancher/k3s:v1.26.4-k3s1
image: docker.io/rancher/k3s:v1.28.4-k3s2
servers: 1
agents: 0
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --disable-cloud-controller
        nodeFilters:
          - server:*
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
