# https://github.com/influxdata/helm-charts/blob/master/charts/influxdb2/values.yaml
influxdb2:
  adminUser:
    existingSecret: influxdb-auth

  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: Influx
      hajimari.io/icon: database
    hostname: &host influxdb.mekanics.ch
    tls: true
    secretName: influxdb-tls-certificate

  persistence:
    enabled: true
    storageClass: 'longhorn'
    size: 10Gi

  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 100m

# https://github.com/influxdata/helm-charts/blob/master/charts/telegraf/values.yaml
telegraf:
  config:
    outputs:
      - influxdb_v2:
          urls:
            - 'http://influx-influxdb2.influx.svc'
          ## Token for authentication.
          token:
            valueFrom:
              secretKeyRef:
                name: influxdb-auth
                key: admin-token
          ## Organization is the name of the organization you wish to write to.
          organization: 'waid'
          ## Destination bucket to write into.
          bucket: 'waid-bucket'

  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 100m
