# https://github.com/influxdata/helm-charts/blob/master/charts/influxdb2/values.yaml
influxdb2:
  adminUser:
    existingSecret: influxdb-auth

  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: mekanics-ca-issuer
      hajimari.io/group: Apps
      hajimari.io/appName: Influx
      hajimari.io/icon: database
    hostname: &host influxdb.mekanics.ch
    tls: true
    secretName: influxdb-tls-certificate

  persistence:
    enabled: true
    storageClass: 'longhorn'
    size: 10Gi

  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 2048Mi
      cpu: 1000m

# https://github.com/influxdata/helm-charts/blob/master/charts/telegraf/values.yaml
telegraf:
  tplVersion: 2
  service:
    enabled: false

  env:
    - name: HOSTNAME
      value: 'telegraf-polling-service'
    - name: INFLUX_TOKEN
      valueFrom:
        secretKeyRef:
          name: influxdb-auth
          key: admin-token

  # https://docs.influxdata.com/telegraf/v1.1/administration/configuration/
  config:
    outputs:
      - influxdb_v2:
          urls:
            - 'http://influx-influxdb2.influx.svc'
          ## Token for authentication.
          token: '$INFLUX_TOKEN'
          ## Organization is the name of the organization you wish to write to.
          organization: 'waid'
          ## Destination bucket to write into.
          bucket: 'waid-bucket'
    inputs:
      - mqtt_consumer:
          servers:
            - 'tcp://mosquitto.mosquitto.svc.cluster.local:1883'
          topics:
            - 'solar/dtu/+'
            - 'solar/+/device/+'
            - 'solar/+/status/+'
            - 'solar/+/0/+'
            - 'solar/+/1/+'
            - 'solar/+/2/+'
            - 'solar/+/3/+'
            - 'solar/+/4/+'
          data_format: 'value'
          data_type: 'string'
          topic_parsing:
            - topic: 'solar/dtu/+'
              measurement: '_/measurement/_'
              tags: '_/_/field'

            - topic: 'solar/+/device/+'
              measurement: '_/_/measurement/_'
              tags: '_/serial/_/field'

            - topic: 'solar/+/status/+'
              measurement: '_/_/measurement/_'
              tags: '_/serial/_/field'

            - topic: 'solar/+/0/+'
              measurement: 'measurement/_/_/_'
              tags: '_/serial/channel/field'

            - topic: 'solar/+/1/+'
              measurement: 'measurement/_/_/_'
              tags: '_/serial/channel/field'

            - topic: 'solar/+/2/+'
              measurement: 'measurement/_/_/_'
              tags: '_/serial/channel/field'

            - topic: 'solar/+/3/+'
              measurement: 'measurement/_/_/_'
              tags: '_/serial/channel/field'

            - topic: 'solar/+/4/+'
              measurement: 'measurement/_/_/_'
              tags: '_/serial/channel/field'

      - mqtt_consumer:
          servers:
            - 'tcp://mosquitto.mosquitto.svc.cluster.local:1883'
          topics:
            - 'main-power/status/#'
          data_format: 'json'

    processors:
      - converter:
          order: 2
          fields:
            string:
              - 'ip'
              - 'hostname'
              - 'status'
              - 'name'
            integer:
              - 'uptime'
              - 'producing'
              - 'reachable'
            float:
              - 'rssi'
              - 'current'
              - 'efficiency'
              - 'frequency'
              - 'power'
              - 'powerdc'
              - 'powerfactor'
              - 'reactivepower'
              - 'temperature'
              - 'irradiation'
              - 'voltage'
              - 'yieldday'
              - 'yieldtotal'
              - 'limit_absolute'
              - 'limit_relative'
      - pivot:
          order: 1
          tag_key: 'field'
          value_key: 'value'

  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 100m
