# https://github.com/influxdata/helm-charts/blob/master/charts/influxdb2/values.yaml
influxdb2:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: Influx
      hajimari.io/icon: database
    hosts:
      - host: &host influxdb.mekanics.ch
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - *host
        secretName: influxdb-tls-certificate

  persistence:
    enabled: true
    storageClass: 'longhorn'
    size: 10Gi
