# https://github.com/influxdata/helm-charts/blob/master/charts/influxdb2/values.yaml
influxdb2:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: Influx
      hajimari.io/icon: database
    hostname: &host influxdb.mekanics.ch
    tls:
      - hosts:
          - *host
        secretName: influxdb-tls-certificate

  persistence:
    enabled: true
    storageClass: 'longhorn'
    size: 10Gi

  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 100m

# https://github.com/influxdata/helm-charts/blob/master/charts/telegraf/values.yaml
telegraf:
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 100m
