# https://github.com/mekanics/charts/blob/main/charts/paperless/values.yaml
paperless:
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 64m
      cert-manager.io/cluster-issuer: mekanics-ca-issuer
      hajimari.io/appName: Paperless
      hajimari.io/icon: file-document
    hosts:
      - host: &host paperless.mekanics.ch
        paths:
          - path: /
            pathType: Prefix
            service: main
    tls:
      - secretName: paperless-tls-certificate
        hosts:
          - *host

  # https://docs.paperless-ngx.com/configuration/
  env:
    - name: TZ
      value: Europe/Zurich
    - name: PAPERLESS_OCR_LANGUAGE
      value: deu+eng
    - name: PAPERLESS_FILENAME_FORMAT
      value: '{correspondent}/{created_year}/{created}_{title}'

  postgresql:
    enabled: false

  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 256Mi

  persistence:
    # -- Configure storage volume settings for the chart under this key.
    storage:
      enabled: true
      existingClaim: 'nfs-paperless-storage'

    # -- Configure export volume settings for the chart under this key.
    export:
      enabled: false
      # existingClaim: ""

    # -- Configure consume volume settings for the chart under this key.
    consume:
      enabled: false
      existingClaim: 'nfs-paperless-consume'
  #
  # postgresql:
  #   enabled: false
  #   auth:
  #     database: paperless
  #     postgresPassword: paperless
  #   primary:
  #     persistence:
  #       enabled: false
  #       # storageClass: ""
  #       # size: 8Gi
