# https://github.com/mekanics/charts/blob/main/charts/paperless/values.yaml
paperless:
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 64m
      cert-manager.io/cluster-issuer: mekanics-ca-issuer
      hajimari.io/group: Apps
      hajimari.io/appName: Paperless
      hajimari.io/icon: file-document
    hosts:
      - host: &host paperless.mekanics.ch
        paths:
          - path: /
            pathType: Prefix
            service: main
    tls:
      - secretName: paperless-tls-certificate
        hosts:
          - *host

  # https://docs.paperless-ngx.com/configuration/
  env:
    - name: TZ
      value: Europe/Zurich
    - name: PAPERLESS_OCR_LANGUAGE
      value: deu+eng
    - name: PAPERLESS_OCR_MODE
      value: skip
    - name: PAPERLESS_OCR_SKIP_ARCHIVE_FILE
      value: with_text
    - name: PAPERLESS_FILENAME_FORMAT
      value: '{{ document_type }}/{{ correspondent }}/{{ created_year }}/{{ created }}_{{ title }}'
    - name: PAPERLESS_CONSUMER_POLLING
      value: 30
    - name: PAPERLESS_TASK_WORKERS
      value: '1'
    - name: PAPERLESS_THREADS_PER_WORKER
      value: '1'
    - name: PAPERLESS_WORKER_TIMEOUT
      value: '1800'
    - name: PAPERLESS_DB_CONN_MAX_AGE
      value: '60'
    - name: PAPERLESS_CONSUMER_DELETE_DUPLICATES
      value: 'true'

  database:
    engine: postgresql
    postgresql:
      host: postgres-cluster-rw.postgres.svc
      port: 5432
      name: paperless
      user: paperless
      existingSecret:
        name: pg-paperless-credentials
        key: password

  resources:
    limits:
      memory: 1536Mi
    requests:
      cpu: 100m
      memory: 512Mi

  persistence:
    # -- Configure storage volume settings for the chart under this key.
    storage:
      enabled: true
      existingClaim: 'nfs-paperless-storage'

    # -- Configure export volume settings for the chart under this key.
    export:
      enabled: false
      # existingClaim: ""

    # -- Configure consume volume settings for the chart under this key.
    consume:
      enabled: true
      existingClaim: 'nfs-paperless-consume'

  extraVolumes:
    - name: log-ephemeral
      emptyDir: {}

  extraVolumeMounts:
    - name: log-ephemeral
      mountPath: /usr/src/paperless/data/log

  podSecurityContext:
    fsGroup: 1000
    runAsNonRoot: true
    runAsGroup: 1000
    runAsUser: 1000

  redis:
    enabled: true
    image:
      repository: bitnamilegacy/redis
    auth:
      enabled: false
    master:
      persistence:
        enabled: false
    replica:
      replicaCount: 0
