apiVersion: v1
kind: PersistentVolume
metadata:
    name: nfs-fava-bside
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteMany
    storageClassName: nfs
    mountOptions:
        - hard
        - nfsvers=4
    nfs:
        server: mercury.local
        path: '/volume1/homelab/finance.bside'
