apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-fava-bside
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  mountOptions:
    - hard
    - intr
    - async
    - noatime
  nfs:
    server: mercury.local
    path: '/volume1/homelab/finance.bside'
