apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-fava-bbi
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  mountOptions:
    - rw
    - nolock
    - tcp
    - async
    - noatime
    - intr
  nfs:
    server: mercury.local
    path: '/volume1/homelab/finance.bbi'
