apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nfs-fava-bbi
spec:
    accessModes:
        - ReadWriteMany
    storageClassName: nfs
    resources:
        requests:
            storage: 500Mi
