# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml

argo-cd:
  server:
    extraArgs:
      - --insecure

    metrics: &metrics
      enabled: true
      serviceMonitor:
        enabled: true

  dex:
    enabled: false
  controller:
    metrics: *metrics
  repoServer:
    metrics: *metrics
  redis:
    metrics: *metrics
