# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml

argo-cd:
  server:
    extraArgs:
      - --insecure
    config:
      statusbadge.enabled: 'true'

    metrics: &metrics
      enabled: true
      serviceMonitor:
        enabled: true

  controller:
    metrics: *metrics

  dex:
    metrics: *metrics

  repoServer:
    metrics: *metrics

  redis:
    metrics: *metrics
